/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as UlasanRouteImport } from './routes/ulasan'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as KomplainRouteImport } from './routes/komplain'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KategoriRouteImport } from './routes/kategori'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as DetailProdukRouteImport } from './routes/detail-produk'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AlamatRouteImport } from './routes/alamat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoucherPenjualRouteImport } from './routes/voucher.penjual'
import { Route as TokoSellerIdRouteImport } from './routes/toko.$sellerId'
import { Route as RegisterPenjualRouteImport } from './routes/register.penjual'
import { Route as RegisterPembeliRouteImport } from './routes/register.pembeli'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'
import { Route as LoginPenjualRouteImport } from './routes/login.penjual'
import { Route as LoginPembeliRouteImport } from './routes/login.pembeli'
import { Route as KomplainPenjualRouteImport } from './routes/komplain.penjual'
import { Route as DashboardPenjualRouteImport } from './routes/dashboard.penjual'
import { Route as DashboardPembeliRouteImport } from './routes/dashboard.pembeli'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as DashboardPenjualProfilTokoRouteImport } from './routes/dashboard.penjual.profil-toko'
import { Route as DashboardPenjualProdukRouteImport } from './routes/dashboard.penjual.produk'
import { Route as DashboardPenjualPesananRouteImport } from './routes/dashboard.penjual.pesanan'
import { Route as DashboardPenjualPengaturanRouteImport } from './routes/dashboard.penjual.pengaturan'
import { Route as DashboardPenjualLaporanRouteImport } from './routes/dashboard.penjual.laporan'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin_.users'
import { Route as DashboardAdminTransaksiRouteImport } from './routes/dashboard.admin_.transaksi'
import { Route as DashboardAdminSellerRouteImport } from './routes/dashboard.admin_.seller'
import { Route as DashboardAdminLaporanRouteImport } from './routes/dashboard.admin_.laporan'
import { Route as DashboardAdminChatRouteImport } from './routes/dashboard.admin_.chat'
import { Route as DashboardPenjualProdukTambahRouteImport } from './routes/dashboard.penjual.produk.tambah'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UlasanRoute = UlasanRouteImport.update({
  id: '/ulasan',
  path: '/ulasan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KomplainRoute = KomplainRouteImport.update({
  id: '/komplain',
  path: '/komplain',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriRoute = KategoriRouteImport.update({
  id: '/kategori',
  path: '/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailProdukRoute = DetailProdukRouteImport.update({
  id: '/detail-produk',
  path: '/detail-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AlamatRoute = AlamatRouteImport.update({
  id: '/alamat',
  path: '/alamat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherPenjualRoute = VoucherPenjualRouteImport.update({
  id: '/voucher/penjual',
  path: '/voucher/penjual',
  getParentRoute: () => rootRouteImport,
} as any)
const TokoSellerIdRoute = TokoSellerIdRouteImport.update({
  id: '/toko/$sellerId',
  path: '/toko/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPenjualRoute = RegisterPenjualRouteImport.update({
  id: '/register/penjual',
  path: '/register/penjual',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPembeliRoute = RegisterPembeliRouteImport.update({
  id: '/register/pembeli',
  path: '/register/pembeli',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProdukRoute,
} as any)
const LoginPenjualRoute = LoginPenjualRouteImport.update({
  id: '/login/penjual',
  path: '/login/penjual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPembeliRoute = LoginPembeliRouteImport.update({
  id: '/login/pembeli',
  path: '/login/pembeli',
  getParentRoute: () => rootRouteImport,
} as any)
const KomplainPenjualRoute = KomplainPenjualRouteImport.update({
  id: '/penjual',
  path: '/penjual',
  getParentRoute: () => KomplainRoute,
} as any)
const DashboardPenjualRoute = DashboardPenjualRouteImport.update({
  id: '/dashboard/penjual',
  path: '/dashboard/penjual',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPembeliRoute = DashboardPembeliRouteImport.update({
  id: '/dashboard/pembeli',
  path: '/dashboard/pembeli',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPenjualProfilTokoRoute =
  DashboardPenjualProfilTokoRouteImport.update({
    id: '/profil-toko',
    path: '/profil-toko',
    getParentRoute: () => DashboardPenjualRoute,
  } as any)
const DashboardPenjualProdukRoute = DashboardPenjualProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => DashboardPenjualRoute,
} as any)
const DashboardPenjualPesananRoute = DashboardPenjualPesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => DashboardPenjualRoute,
} as any)
const DashboardPenjualPengaturanRoute =
  DashboardPenjualPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => DashboardPenjualRoute,
  } as any)
const DashboardPenjualLaporanRoute = DashboardPenjualLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => DashboardPenjualRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/dashboard/admin_/users',
  path: '/dashboard/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminTransaksiRoute = DashboardAdminTransaksiRouteImport.update({
  id: '/dashboard/admin_/transaksi',
  path: '/dashboard/admin/transaksi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminSellerRoute = DashboardAdminSellerRouteImport.update({
  id: '/dashboard/admin_/seller',
  path: '/dashboard/admin/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminLaporanRoute = DashboardAdminLaporanRouteImport.update({
  id: '/dashboard/admin_/laporan',
  path: '/dashboard/admin/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminChatRoute = DashboardAdminChatRouteImport.update({
  id: '/dashboard/admin_/chat',
  path: '/dashboard/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPenjualProdukTambahRoute =
  DashboardPenjualProdukTambahRouteImport.update({
    id: '/tambah',
    path: '/tambah',
    getParentRoute: () => DashboardPenjualProdukRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alamat': typeof AlamatRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/detail-produk': typeof DetailProdukRoute
  '/invoice': typeof InvoiceRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/komplain': typeof KomplainRouteWithChildren
  '/notifikasi': typeof NotifikasiRoute
  '/produk': typeof ProdukRouteWithChildren
  '/profil': typeof ProfilRoute
  '/tentang': typeof TentangRoute
  '/tracking': typeof TrackingRoute
  '/ulasan': typeof UlasanRoute
  '/wishlist': typeof WishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/pembeli': typeof DashboardPembeliRoute
  '/dashboard/penjual': typeof DashboardPenjualRouteWithChildren
  '/komplain/penjual': typeof KomplainPenjualRoute
  '/login/pembeli': typeof LoginPembeliRoute
  '/login/penjual': typeof LoginPenjualRoute
  '/produk/$id': typeof ProdukIdRoute
  '/register/pembeli': typeof RegisterPembeliRoute
  '/register/penjual': typeof RegisterPenjualRoute
  '/toko/$sellerId': typeof TokoSellerIdRoute
  '/voucher/penjual': typeof VoucherPenjualRoute
  '/dashboard/admin/chat': typeof DashboardAdminChatRoute
  '/dashboard/admin/laporan': typeof DashboardAdminLaporanRoute
  '/dashboard/admin/seller': typeof DashboardAdminSellerRoute
  '/dashboard/admin/transaksi': typeof DashboardAdminTransaksiRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/penjual/laporan': typeof DashboardPenjualLaporanRoute
  '/dashboard/penjual/pengaturan': typeof DashboardPenjualPengaturanRoute
  '/dashboard/penjual/pesanan': typeof DashboardPenjualPesananRoute
  '/dashboard/penjual/produk': typeof DashboardPenjualProdukRouteWithChildren
  '/dashboard/penjual/profil-toko': typeof DashboardPenjualProfilTokoRoute
  '/dashboard/penjual/produk/tambah': typeof DashboardPenjualProdukTambahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alamat': typeof AlamatRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/detail-produk': typeof DetailProdukRoute
  '/invoice': typeof InvoiceRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/komplain': typeof KomplainRouteWithChildren
  '/notifikasi': typeof NotifikasiRoute
  '/produk': typeof ProdukRouteWithChildren
  '/profil': typeof ProfilRoute
  '/tentang': typeof TentangRoute
  '/tracking': typeof TrackingRoute
  '/ulasan': typeof UlasanRoute
  '/wishlist': typeof WishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/pembeli': typeof DashboardPembeliRoute
  '/dashboard/penjual': typeof DashboardPenjualRouteWithChildren
  '/komplain/penjual': typeof KomplainPenjualRoute
  '/login/pembeli': typeof LoginPembeliRoute
  '/login/penjual': typeof LoginPenjualRoute
  '/produk/$id': typeof ProdukIdRoute
  '/register/pembeli': typeof RegisterPembeliRoute
  '/register/penjual': typeof RegisterPenjualRoute
  '/toko/$sellerId': typeof TokoSellerIdRoute
  '/voucher/penjual': typeof VoucherPenjualRoute
  '/dashboard/admin/chat': typeof DashboardAdminChatRoute
  '/dashboard/admin/laporan': typeof DashboardAdminLaporanRoute
  '/dashboard/admin/seller': typeof DashboardAdminSellerRoute
  '/dashboard/admin/transaksi': typeof DashboardAdminTransaksiRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/penjual/laporan': typeof DashboardPenjualLaporanRoute
  '/dashboard/penjual/pengaturan': typeof DashboardPenjualPengaturanRoute
  '/dashboard/penjual/pesanan': typeof DashboardPenjualPesananRoute
  '/dashboard/penjual/produk': typeof DashboardPenjualProdukRouteWithChildren
  '/dashboard/penjual/profil-toko': typeof DashboardPenjualProfilTokoRoute
  '/dashboard/penjual/produk/tambah': typeof DashboardPenjualProdukTambahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alamat': typeof AlamatRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/detail-produk': typeof DetailProdukRoute
  '/invoice': typeof InvoiceRoute
  '/kategori': typeof KategoriRoute
  '/keranjang': typeof KeranjangRoute
  '/komplain': typeof KomplainRouteWithChildren
  '/notifikasi': typeof NotifikasiRoute
  '/produk': typeof ProdukRouteWithChildren
  '/profil': typeof ProfilRoute
  '/tentang': typeof TentangRoute
  '/tracking': typeof TrackingRoute
  '/ulasan': typeof UlasanRoute
  '/wishlist': typeof WishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/pembeli': typeof DashboardPembeliRoute
  '/dashboard/penjual': typeof DashboardPenjualRouteWithChildren
  '/komplain/penjual': typeof KomplainPenjualRoute
  '/login/pembeli': typeof LoginPembeliRoute
  '/login/penjual': typeof LoginPenjualRoute
  '/produk/$id': typeof ProdukIdRoute
  '/register/pembeli': typeof RegisterPembeliRoute
  '/register/penjual': typeof RegisterPenjualRoute
  '/toko/$sellerId': typeof TokoSellerIdRoute
  '/voucher/penjual': typeof VoucherPenjualRoute
  '/dashboard/admin_/chat': typeof DashboardAdminChatRoute
  '/dashboard/admin_/laporan': typeof DashboardAdminLaporanRoute
  '/dashboard/admin_/seller': typeof DashboardAdminSellerRoute
  '/dashboard/admin_/transaksi': typeof DashboardAdminTransaksiRoute
  '/dashboard/admin_/users': typeof DashboardAdminUsersRoute
  '/dashboard/penjual/laporan': typeof DashboardPenjualLaporanRoute
  '/dashboard/penjual/pengaturan': typeof DashboardPenjualPengaturanRoute
  '/dashboard/penjual/pesanan': typeof DashboardPenjualPesananRoute
  '/dashboard/penjual/produk': typeof DashboardPenjualProdukRouteWithChildren
  '/dashboard/penjual/profil-toko': typeof DashboardPenjualProfilTokoRoute
  '/dashboard/penjual/produk/tambah': typeof DashboardPenjualProdukTambahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alamat'
    | '/chat'
    | '/checkout'
    | '/detail-produk'
    | '/invoice'
    | '/kategori'
    | '/keranjang'
    | '/komplain'
    | '/notifikasi'
    | '/produk'
    | '/profil'
    | '/tentang'
    | '/tracking'
    | '/ulasan'
    | '/wishlist'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/pembeli'
    | '/dashboard/penjual'
    | '/komplain/penjual'
    | '/login/pembeli'
    | '/login/penjual'
    | '/produk/$id'
    | '/register/pembeli'
    | '/register/penjual'
    | '/toko/$sellerId'
    | '/voucher/penjual'
    | '/dashboard/admin/chat'
    | '/dashboard/admin/laporan'
    | '/dashboard/admin/seller'
    | '/dashboard/admin/transaksi'
    | '/dashboard/admin/users'
    | '/dashboard/penjual/laporan'
    | '/dashboard/penjual/pengaturan'
    | '/dashboard/penjual/pesanan'
    | '/dashboard/penjual/produk'
    | '/dashboard/penjual/profil-toko'
    | '/dashboard/penjual/produk/tambah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alamat'
    | '/chat'
    | '/checkout'
    | '/detail-produk'
    | '/invoice'
    | '/kategori'
    | '/keranjang'
    | '/komplain'
    | '/notifikasi'
    | '/produk'
    | '/profil'
    | '/tentang'
    | '/tracking'
    | '/ulasan'
    | '/wishlist'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/pembeli'
    | '/dashboard/penjual'
    | '/komplain/penjual'
    | '/login/pembeli'
    | '/login/penjual'
    | '/produk/$id'
    | '/register/pembeli'
    | '/register/penjual'
    | '/toko/$sellerId'
    | '/voucher/penjual'
    | '/dashboard/admin/chat'
    | '/dashboard/admin/laporan'
    | '/dashboard/admin/seller'
    | '/dashboard/admin/transaksi'
    | '/dashboard/admin/users'
    | '/dashboard/penjual/laporan'
    | '/dashboard/penjual/pengaturan'
    | '/dashboard/penjual/pesanan'
    | '/dashboard/penjual/produk'
    | '/dashboard/penjual/profil-toko'
    | '/dashboard/penjual/produk/tambah'
  id:
    | '__root__'
    | '/'
    | '/alamat'
    | '/chat'
    | '/checkout'
    | '/detail-produk'
    | '/invoice'
    | '/kategori'
    | '/keranjang'
    | '/komplain'
    | '/notifikasi'
    | '/produk'
    | '/profil'
    | '/tentang'
    | '/tracking'
    | '/ulasan'
    | '/wishlist'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/pembeli'
    | '/dashboard/penjual'
    | '/komplain/penjual'
    | '/login/pembeli'
    | '/login/penjual'
    | '/produk/$id'
    | '/register/pembeli'
    | '/register/penjual'
    | '/toko/$sellerId'
    | '/voucher/penjual'
    | '/dashboard/admin_/chat'
    | '/dashboard/admin_/laporan'
    | '/dashboard/admin_/seller'
    | '/dashboard/admin_/transaksi'
    | '/dashboard/admin_/users'
    | '/dashboard/penjual/laporan'
    | '/dashboard/penjual/pengaturan'
    | '/dashboard/penjual/pesanan'
    | '/dashboard/penjual/produk'
    | '/dashboard/penjual/profil-toko'
    | '/dashboard/penjual/produk/tambah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlamatRoute: typeof AlamatRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  DetailProdukRoute: typeof DetailProdukRoute
  InvoiceRoute: typeof InvoiceRoute
  KategoriRoute: typeof KategoriRoute
  KeranjangRoute: typeof KeranjangRoute
  KomplainRoute: typeof KomplainRouteWithChildren
  NotifikasiRoute: typeof NotifikasiRoute
  ProdukRoute: typeof ProdukRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  TentangRoute: typeof TentangRoute
  TrackingRoute: typeof TrackingRoute
  UlasanRoute: typeof UlasanRoute
  WishlistRoute: typeof WishlistRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardPembeliRoute: typeof DashboardPembeliRoute
  DashboardPenjualRoute: typeof DashboardPenjualRouteWithChildren
  LoginPembeliRoute: typeof LoginPembeliRoute
  LoginPenjualRoute: typeof LoginPenjualRoute
  RegisterPembeliRoute: typeof RegisterPembeliRoute
  RegisterPenjualRoute: typeof RegisterPenjualRoute
  TokoSellerIdRoute: typeof TokoSellerIdRoute
  VoucherPenjualRoute: typeof VoucherPenjualRoute
  DashboardAdminChatRoute: typeof DashboardAdminChatRoute
  DashboardAdminLaporanRoute: typeof DashboardAdminLaporanRoute
  DashboardAdminSellerRoute: typeof DashboardAdminSellerRoute
  DashboardAdminTransaksiRoute: typeof DashboardAdminTransaksiRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulasan': {
      id: '/ulasan'
      path: '/ulasan'
      fullPath: '/ulasan'
      preLoaderRoute: typeof UlasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komplain': {
      id: '/komplain'
      path: '/komplain'
      fullPath: '/komplain'
      preLoaderRoute: typeof KomplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori': {
      id: '/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof KategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail-produk': {
      id: '/detail-produk'
      path: '/detail-produk'
      fullPath: '/detail-produk'
      preLoaderRoute: typeof DetailProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alamat': {
      id: '/alamat'
      path: '/alamat'
      fullPath: '/alamat'
      preLoaderRoute: typeof AlamatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/penjual': {
      id: '/voucher/penjual'
      path: '/voucher/penjual'
      fullPath: '/voucher/penjual'
      preLoaderRoute: typeof VoucherPenjualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toko/$sellerId': {
      id: '/toko/$sellerId'
      path: '/toko/$sellerId'
      fullPath: '/toko/$sellerId'
      preLoaderRoute: typeof TokoSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/penjual': {
      id: '/register/penjual'
      path: '/register/penjual'
      fullPath: '/register/penjual'
      preLoaderRoute: typeof RegisterPenjualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/pembeli': {
      id: '/register/pembeli'
      path: '/register/pembeli'
      fullPath: '/register/pembeli'
      preLoaderRoute: typeof RegisterPembeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof ProdukRoute
    }
    '/login/penjual': {
      id: '/login/penjual'
      path: '/login/penjual'
      fullPath: '/login/penjual'
      preLoaderRoute: typeof LoginPenjualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/pembeli': {
      id: '/login/pembeli'
      path: '/login/pembeli'
      fullPath: '/login/pembeli'
      preLoaderRoute: typeof LoginPembeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komplain/penjual': {
      id: '/komplain/penjual'
      path: '/penjual'
      fullPath: '/komplain/penjual'
      preLoaderRoute: typeof KomplainPenjualRouteImport
      parentRoute: typeof KomplainRoute
    }
    '/dashboard/penjual': {
      id: '/dashboard/penjual'
      path: '/dashboard/penjual'
      fullPath: '/dashboard/penjual'
      preLoaderRoute: typeof DashboardPenjualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pembeli': {
      id: '/dashboard/pembeli'
      path: '/dashboard/pembeli'
      fullPath: '/dashboard/pembeli'
      preLoaderRoute: typeof DashboardPembeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/penjual/profil-toko': {
      id: '/dashboard/penjual/profil-toko'
      path: '/profil-toko'
      fullPath: '/dashboard/penjual/profil-toko'
      preLoaderRoute: typeof DashboardPenjualProfilTokoRouteImport
      parentRoute: typeof DashboardPenjualRoute
    }
    '/dashboard/penjual/produk': {
      id: '/dashboard/penjual/produk'
      path: '/produk'
      fullPath: '/dashboard/penjual/produk'
      preLoaderRoute: typeof DashboardPenjualProdukRouteImport
      parentRoute: typeof DashboardPenjualRoute
    }
    '/dashboard/penjual/pesanan': {
      id: '/dashboard/penjual/pesanan'
      path: '/pesanan'
      fullPath: '/dashboard/penjual/pesanan'
      preLoaderRoute: typeof DashboardPenjualPesananRouteImport
      parentRoute: typeof DashboardPenjualRoute
    }
    '/dashboard/penjual/pengaturan': {
      id: '/dashboard/penjual/pengaturan'
      path: '/pengaturan'
      fullPath: '/dashboard/penjual/pengaturan'
      preLoaderRoute: typeof DashboardPenjualPengaturanRouteImport
      parentRoute: typeof DashboardPenjualRoute
    }
    '/dashboard/penjual/laporan': {
      id: '/dashboard/penjual/laporan'
      path: '/laporan'
      fullPath: '/dashboard/penjual/laporan'
      preLoaderRoute: typeof DashboardPenjualLaporanRouteImport
      parentRoute: typeof DashboardPenjualRoute
    }
    '/dashboard/admin_/users': {
      id: '/dashboard/admin_/users'
      path: '/dashboard/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin_/transaksi': {
      id: '/dashboard/admin_/transaksi'
      path: '/dashboard/admin/transaksi'
      fullPath: '/dashboard/admin/transaksi'
      preLoaderRoute: typeof DashboardAdminTransaksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin_/seller': {
      id: '/dashboard/admin_/seller'
      path: '/dashboard/admin/seller'
      fullPath: '/dashboard/admin/seller'
      preLoaderRoute: typeof DashboardAdminSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin_/laporan': {
      id: '/dashboard/admin_/laporan'
      path: '/dashboard/admin/laporan'
      fullPath: '/dashboard/admin/laporan'
      preLoaderRoute: typeof DashboardAdminLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin_/chat': {
      id: '/dashboard/admin_/chat'
      path: '/dashboard/admin/chat'
      fullPath: '/dashboard/admin/chat'
      preLoaderRoute: typeof DashboardAdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/penjual/produk/tambah': {
      id: '/dashboard/penjual/produk/tambah'
      path: '/tambah'
      fullPath: '/dashboard/penjual/produk/tambah'
      preLoaderRoute: typeof DashboardPenjualProdukTambahRouteImport
      parentRoute: typeof DashboardPenjualProdukRoute
    }
  }
}

interface KomplainRouteChildren {
  KomplainPenjualRoute: typeof KomplainPenjualRoute
}

const KomplainRouteChildren: KomplainRouteChildren = {
  KomplainPenjualRoute: KomplainPenjualRoute,
}

const KomplainRouteWithChildren = KomplainRoute._addFileChildren(
  KomplainRouteChildren,
)

interface ProdukRouteChildren {
  ProdukIdRoute: typeof ProdukIdRoute
}

const ProdukRouteChildren: ProdukRouteChildren = {
  ProdukIdRoute: ProdukIdRoute,
}

const ProdukRouteWithChildren =
  ProdukRoute._addFileChildren(ProdukRouteChildren)

interface DashboardPenjualProdukRouteChildren {
  DashboardPenjualProdukTambahRoute: typeof DashboardPenjualProdukTambahRoute
}

const DashboardPenjualProdukRouteChildren: DashboardPenjualProdukRouteChildren =
  {
    DashboardPenjualProdukTambahRoute: DashboardPenjualProdukTambahRoute,
  }

const DashboardPenjualProdukRouteWithChildren =
  DashboardPenjualProdukRoute._addFileChildren(
    DashboardPenjualProdukRouteChildren,
  )

interface DashboardPenjualRouteChildren {
  DashboardPenjualLaporanRoute: typeof DashboardPenjualLaporanRoute
  DashboardPenjualPengaturanRoute: typeof DashboardPenjualPengaturanRoute
  DashboardPenjualPesananRoute: typeof DashboardPenjualPesananRoute
  DashboardPenjualProdukRoute: typeof DashboardPenjualProdukRouteWithChildren
  DashboardPenjualProfilTokoRoute: typeof DashboardPenjualProfilTokoRoute
}

const DashboardPenjualRouteChildren: DashboardPenjualRouteChildren = {
  DashboardPenjualLaporanRoute: DashboardPenjualLaporanRoute,
  DashboardPenjualPengaturanRoute: DashboardPenjualPengaturanRoute,
  DashboardPenjualPesananRoute: DashboardPenjualPesananRoute,
  DashboardPenjualProdukRoute: DashboardPenjualProdukRouteWithChildren,
  DashboardPenjualProfilTokoRoute: DashboardPenjualProfilTokoRoute,
}

const DashboardPenjualRouteWithChildren =
  DashboardPenjualRoute._addFileChildren(DashboardPenjualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlamatRoute: AlamatRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  DetailProdukRoute: DetailProdukRoute,
  InvoiceRoute: InvoiceRoute,
  KategoriRoute: KategoriRoute,
  KeranjangRoute: KeranjangRoute,
  KomplainRoute: KomplainRouteWithChildren,
  NotifikasiRoute: NotifikasiRoute,
  ProdukRoute: ProdukRouteWithChildren,
  ProfilRoute: ProfilRoute,
  TentangRoute: TentangRoute,
  TrackingRoute: TrackingRoute,
  UlasanRoute: UlasanRoute,
  WishlistRoute: WishlistRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardPembeliRoute: DashboardPembeliRoute,
  DashboardPenjualRoute: DashboardPenjualRouteWithChildren,
  LoginPembeliRoute: LoginPembeliRoute,
  LoginPenjualRoute: LoginPenjualRoute,
  RegisterPembeliRoute: RegisterPembeliRoute,
  RegisterPenjualRoute: RegisterPenjualRoute,
  TokoSellerIdRoute: TokoSellerIdRoute,
  VoucherPenjualRoute: VoucherPenjualRoute,
  DashboardAdminChatRoute: DashboardAdminChatRoute,
  DashboardAdminLaporanRoute: DashboardAdminLaporanRoute,
  DashboardAdminSellerRoute: DashboardAdminSellerRoute,
  DashboardAdminTransaksiRoute: DashboardAdminTransaksiRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
